name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -Prelease=${{  github.ref_name }} --info
        env:
          EXAROTON_API_TOKEN: ${{ secrets.EXAROTON_API_KEY }}
          EXAROTON_TEST_SERVER: "WgvSsfR8ZizUO1RQ"
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.EXAROTON_GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PASSPHRASE: ${{ secrets.EXAROTON_GPG_SIGNING_PASSPHRASE }}
          ORG_GRADLE_PROJECT_OSSRH_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
          EXAROTON_API_TOKEN: ${{ secrets.EXAROTON_API_KEY }}
          EXAROTON_TEST_SERVER: "WgvSsfR8ZizUO1RQ"
        run: ./gradlew publish -Prelease=${{ github.ref_name }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/libs/mclogs-*.jar
          body_path: ${{ github.workspace }}/CHANGELOG.md
          name: ${{ github.ref_name }}