name: Test

on:
  push:
    branches:
      - '*'
  pull_request:

concurrency:
  group: java-exaroton-api

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build --info
        env:
          EXAROTON_API_TOKEN: ${{ secrets.EXAROTON_API_KEY }}
          EXAROTON_TEST_SERVER: "WgvSsfR8ZizUO1RQ"
          EXAROTON_TEST_POOL: "N2t9gWOMpzRL37FI"
